### PR TITLE
Add support for Seurat v3

### PR DESCRIPTION
**Pull request by mojaveazure**
Now that [Seurat v3 is on CRAN](https://cran.r-project.org/web/packages/Seurat/index.html), I'm going through the packages that import or depend on Seurat to help ease the transition from the Seurat v2 (`seurat`) object to the v3 (`Seurat`) object.

- Add methods for `clustree` and `clustree_overlay` for `Seurat` objects
- Use Seurat's accessors for pulling data from the object
- Adjust tests and the vignette to use `Seurat` objects

### CODE REVIEW

**Comment by mojaveazure** [comment]
Forgot to add my `R CMD check` log

[00check.log](https://github.com/lazappi/clustree/files/3082320/00check.log)

**Comment by lazappi** [comment]
Hi @mojaveazure 

Congratulations on all the work on Seurat v3 and getting it on CRAN! I knew this was going to be an issue but I hadn't got around to looking at it yet so thanks for the PR, that will make my life a lot easier.

There are a few changes I would like to make to what you have provided. Do you want to be involved in that, or are you happy for me to merge and take it from there?

I'd also like to add you to the DESCRIPTION as a contributor. I can get your details from the Seurat DESCRIPTION unless you would like something different (or you prefer to not be included).

**Comment by mojaveazure** [comment]
Hi Luke,

Thank you! I made this primarily to provide a jumping off point following the best practices (from our, completely biased opinion) when using the Seurat v3 object (eg. accessors and setters such as the `[[` operator for meta data, support for multimodal data, etc).

If you have any changes to better fit your code, I highly encourage them. If you'd like help, I'd be happy to, especially with Seurat-specific stuff. Otherwise, I trust your ability to modify what I've done to fit your codebase.

If you'd like to add me as a contributor, I would ask that you use my actual email address (found on [Rahul's website](https://satijalab.org) or in the DESCRIPTION for [loomR](https://github.com/mojaveazure/loomR). My email in Seurat is used only for Seurat maintenance and isn't truly associated with me.

**Comment by lazappi** [comment]
Cool! I want to get this up on CRAN fairly quickly before people try and use it so I'm going to merge this and work on it a bit. I might run it by you again to check the Seurat stuff when I'm done.

**Comment by lazappi** [comment]
I've added these changes to the `develop` branch. I'll probably submit it tomorrow but feel free to have a look and make any suggestions before then if you are interested.

**Pull request merged**
