### PR TITLE
Added control of the node text rotation

### PR DESCRIPTION
**Pull request by kvittingseerup**
As you suggested in #79

### CODE REVIEW

**Comment by lazappi** [comment]
Thanks! I've had a quick look at this and it seems to work. Couple of comments:

- Could you please make a similar change to the `clustree_overlay()` function? I try to keep this in sync with `clustree()` as much as possible.
- I have a policy of trying to include everyone who contributes to **{clustree}** as an author. If you are happy to do that please add your details to the authors list in `DESCRIPTION` and the contributors list in `README.md`.

**Comment by kvittingseerup** [comment]
Ah sorry - was not aware of the `clustree_overlay()` function :-)

That does however cause a small problem as `geom_label_repel()` apparently[ does not support rotation](https://stackoverflow.com/questions/47921805/how-to-use-angle-in-geom-label). 

Seems it would require switching to `geom_text_repel()` or `geom_richtext()`. Would that be acceptable or would you prefer it without the rotation option?

Thanks for the author offer - I do think this update is to small to qualify for that though :-)

**Comment by lazappi** [comment]
> Ah sorry - was not aware of the `clustree_overlay()` function :-)
> 
> That does however cause a small problem as `geom_label_repel()` apparently[ does not support rotation](https://stackoverflow.com/questions/47921805/how-to-use-angle-in-geom-label).
> 
> Seems it would require switching to `geom_text_repel()` or `geom_richtext()`. Would that be acceptable or would you prefer it without the rotation option?

Ah, ok. In that case don't worry about it.

> Thanks for the author offer - I do think this update is to small to qualify for that though :-)

Definitely not too small but if you would prefer not to that's up to you. You could just do the `README` list if you like.

**Comment by kvittingseerup** [comment]
Again thanks for the author offer but I'll pass :)

Do you have an idea when the updated version will be on CRAN?

**Comment by lazappi** [comment]
I will try to submit it in the next day or so and assuming everything passes it should be up next week sometime. I am on leave from the end of next week though so if it doesn't happen by then it will be a while longer.

**Pull request merged**
